version: '3.7'
services:
  devtool:
    build:
      context: './devtool'
    tty: true
    volumes:
      - './git_repository:/root/git_repository'
      - '.:/root/workspace'
      - '~/.ssh:/root/.ssh'
      - './devtool/config/fish:/root/.config/fish'
      - './devtool/local/fish:/root/.local/share/fish'
    working_dir: '/root'
